<!--
    小车底盘添加雷达
-->
<robot name="laser_of_redcar" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- 雷达支架 -->
    <xacro:property name="support_length" value="0.06" /> <!-- 支架 长 -->
    <xacro:property name="support_width" value="0.06" /> <!-- 支架 宽 -->
    <xacro:property name="support_height" value="0.06" /> <!-- 支架 高 -->
    <xacro:property name="support_x" value="-0.375" /> <!-- 支架安装的x坐标 -->
    <xacro:property name="support_y" value="0.0" /> <!-- 支架安装的y坐标 -->
    <xacro:property name="support_z" value="${car_body_height / 2 + support_height / 2}" /> <!-- 支架安装的z坐标:底盘高度 / 2 + 支架高度 / 2  -->

    <link name="support_laser">
        <visual>
            <geometry>
                <box size="${support_length} ${support_width} ${support_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="blue">
                <color rgba="0 0 1 1" />
            </material>
        </visual>
    </link>

    <joint name="support2car_body" type="fixed">
        <parent link="car_body" />
        <child link="support_laser" />
        <origin xyz="${support_x} ${support_y} ${support_z}" />
    </joint>


    <!-- 雷达属性 -->
    <xacro:property name="laser_length" value="0.042" /> <!-- 雷达长度 -->
    <xacro:property name="laser_radius" value="0.02" /> <!-- 雷达半径 -->
    <xacro:property name="laser_x" value="0" /> <!-- 雷达安装的x坐标 -->
    <xacro:property name="laser_y" value="0.0" /> <!-- 雷达安装的y坐标 -->
    <xacro:property name="laser_z" value="${support_height / 2 + laser_length / 2}" /> <!-- 雷达安装的z坐标:支架高度 / 2 + 雷达高度 / 2  -->

    <!-- 雷达关节以及link -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
    </link>

    <joint name="laser2support" type="fixed">
        <parent link="support_laser" />
        <child link="laser" />
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" />
    </joint>
</robot>
