<!-- 摄像头相关的 xacro 文件 -->
<robot name="imu_of_redcar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 摄像头属性 -->
    <xacro:property name="imu_length" value="0.03" /> <!-- imu 长 -->
    <xacro:property name="imu_width" value="0.04" /> <!-- imu 宽 -->
    <xacro:property name="imu_height" value="0.01" /> <!-- imu 高 -->
    <xacro:property name="imu_x" value="-0.375" /> <!-- 摄像头安装的x坐标 -->
    <xacro:property name="imu_y" value="0.3" /> <!-- 摄像头安装的y坐标 -->
    <xacro:property name="imu_z" value="${car_body_height / 2 + imu_height / 2}" /> <!-- 摄像头安装的z坐标:底盘高度 / 2 + 摄像头高度 / 2  -->

    <!-- 摄像头关节以及link -->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="green">
                <color rgba="0 1 0 1"/>
            </material>
        </visual>
    </link>

    <joint name="camera2base_link" type="fixed">
        <parent link="car_body" />
        <child link="imu_link" />
        <origin xyz="${imu_x} ${imu_y} ${imu_z}" />
    </joint>
</robot>
