<robot name="redcar_laser" xmlns:xacro="http://wiki.ros.org/xacro">


    <xacro:property name="support_length" value="0.06" /> 
    <xacro:property name="support_width" value="0.06" />
    <xacro:property name="support_height" value="0.06" />
    <xacro:property name="support_x" value="-0.375" />
    <xacro:property name="support_y" value="0.0" />
    <xacro:property name="support_z" value="${base_link_height / 2 + support_height / 2}" />

    <xacro:property name="support_m" value="0.1" />

    <link name="support_laser">
        <visual>
            <geometry>
                <box size="${support_length} ${support_width} ${support_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="blue">
                <color rgba="0 0 1 1" />
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${support_length} ${support_width} ${support_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:Box_inertial_matrix m="${support_m}" l="${support_length}" w="${support_width}" h="${support_height}" />

    </link>

    <joint name="support2base_link" type="fixed">
        <parent link="base_link" />
        <child link="support_laser" />
        <origin xyz="${support_x} ${support_y} ${support_z}" />
    </joint>

    <gazebo reference="support_laser">
        <material>Gazebo/Blue</material>
    </gazebo>


    <xacro:property name="laser_length" value="0.042" />
    <xacro:property name="laser_radius" value="0.02" />
    <xacro:property name="laser_x" value="0" />
    <xacro:property name="laser_y" value="0.0" />
    <xacro:property name="laser_z" value="${support_height / 2 + laser_length / 2}" />

    <xacro:property name="laser_m" value="0.1" />


    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
 
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />

    </link>

    <joint name="laser2support" type="fixed">
        <parent link="support_laser" />
        <child link="laser" />
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" />
    </joint>

    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>
