<robot name="redcar_imu" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="imu_length" value="0.03" />
    <xacro:property name="imu_width" value="0.04" />
    <xacro:property name="imu_height" value="0.01" />
    <xacro:property name="imu_x" value="-0.375" />
    <xacro:property name="imu_y" value="${base_link_width / 2 - imu_width / 2}" />
    <xacro:property name="imu_z" value="${base_link_height / 2 + imu_height / 2}" />

    <xacro:property name="imu_m" value="0.01" />


    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
 
        <collision>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:Box_inertial_matrix m="${imu_m}" l="${imu_length}" w="${imu_width}" h="${imu_height}" />

    </link>

    <joint name="imu_link2base_link" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="${imu_x} ${imu_y} ${imu_z}" />
    </joint>

    <gazebo reference="imu_link">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>
